name: 普通发布
on:
  issues:
    types: [closed]
permissions:
  contents: write
jobs:
  publish:
    if: "!contains(github.event.issue.labels.*.name, 'resource-request')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          draft: false
          prerelease: false

